version: '3'

services:
  backend:
    image: lolobens_backend:latest
    ports:
      - "8000:8000"
    volumes:
      - lolobens-volume:/backend/database/db
      - ./backend:/backend
    command: "tail -f /dev/null"
    env_file:
      - ./env/dev.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - lolobens-postgres:/var/lib/postgresql/data
    env_file:
      - ./env/dev.env

  email:
    image: lolobens_email:latest
    restart: always
    command: 'python manage.py send_mail'
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    env_file:
      - ./env/dev.env
    depends_on:
      - postgres
      - backend

volumes:
  lolobens-volume:
  lolobens-postgres:
  media-files:
  static-files:
